#!/bin/bash

pip install -q QUnitSuite flake8 coveralls pylint > /dev/null 2>&1

# We can exit here and do nothing if this only a LINT check
if [ "${LINT_CHECK}" == "1" ] ; then
    exit 0
fi

# For backward compatibility, take version from parameter if it's not globally set
if [ "x${VERSION}" == "x" ] ; then
    VERSION="${1}"
    echo "WARNING: no env variable set for VERSION. Using '${1}'."
fi

: ${ODOO_REPO:="odoo/odoo"}  # default value, if not set
IFS="/" read -a REPO <<< "${ODOO_REPO}"
ODOO_URL="https://github.com/${REPO[0]}/${REPO[1]}/archive/${VERSION}.tar.gz"

echo "Installing Odoo ${ODOO_URL}"
wget -nv -O odoo.tar.gz ${ODOO_URL}
tar -xf odoo.tar.gz -C ${HOME}

echo "Installing Python dependencies"
sudo apt-get -qq -y install expect-dev  # provides unbuffer utility
# sudo apt-get -qq -y install python-lxml  # Commented because lxml default version on Ubuntu 14.10 is broken.
# From source lxml
kernel_release=$( uname -r )
#sudo apt-get install linux-headers-${kernel_release} build-essential -y
#sudo apt-get install libxml2-dev libxslt1-dev cython -y
#git clone --branch lxml-3.3.3 https://github.com/lxml/lxml
#cd xml
#python2.7 setup.py clean build --with-cython install
###################

# Workaround to force using system site packages (see https://github.com/Shippable/support/issues/241#issuecomment-57947925)
rm -f $VIRTUAL_ENV/lib/python2.7/no-global-site-packages.txt

pip install -q -r $(dirname ${BASH_SOURCE[0]})/requirements.txt

# Use reference .coveragerc
cp ${HOME}/maintainer-quality-tools/cfg/.coveragerc .

echo "Getting dependencies"
clone_oca_dependencies

# Expected directory structure:
#
#    HOME/
#     |___ <OdooRepo>-<Branch>/         <-- Odoo Server
#     |___ maintainer-quality-tools/
#     |___ build/<Owner>/<TestedRepo>/
#     |___ <DependencyRepo1>/
#     |___ <DependencyRepo2>/
#     |...
echo "Content of ${HOME}:"
ls -l ${HOME}
